version: '2'
services:
    codedx-db:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=codedx
        volumes:
            - codedx-db-files:/var/lib/mysql
    codedx-tomcat:
        build: ./codedx-tomcat/
        environment:
            - DB_URL=jdbc:mysql://codedx-db/codedx
            - DB_DRIVER=com.mysql.jdbc.Driver
            - DB_USER=root
            - DB_PASSWORD=root
            - SUPERUSER_NAME=admin
            - SUPERUSER_PASSWORD=secret
        volumes:
            - codedx-appdata:/opt/codedx
        ports:
            - 8080:8080
        depends_on:
            - codedx-db
volumes:
    codedx-db-files:
    codedx-appdata:
